# Numpy

In [1]:
import numpy as np

In [2]:
idades = [10,20,30]
print(type(idades))

<class 'list'>


In [3]:
numpyIdades = np.array(idades)
print(type(numpyIdades))

<class 'numpy.ndarray'>


## Multiplicação de Arrays

In [6]:
a = [2,3,4]
resultado = []

# Manualmente
for i in range(len(a)):
    multiplicacao = 2*a[i]
    resultado.append(multiplicacao)

print(a)
print(resultado)

[2, 3, 4]
[4, 6, 8]


In [7]:
# Usando numpy
np_a = np.array(a)
np_resultado = np_a*2
print(np_a)
print(np_resultado)

[2 3 4]
[4 6 8]


## Média e Soma

In [9]:
anos = [
    1985,
    1990,
    2000,
    2005,
    1970,
    2015,
    1951,
    1988
]

anos = np.array(anos)

In [15]:
idades = 2023 - anos

print(anos)
print(idades)
print(idades.sum())
print(idades.sum()/len(idades))
print(idades.sum()/idades.size)
print(np.average(idades))

print()

print(idades.ndim)

[1985 1990 2000 2005 1970 2015 1951 1988]
[38 33 23 18 53  8 72 35]
280
35.0
35.0
35.0

1


## Desempenho em Tempo

In [17]:
import time 

total = 10000
inicio = time.time()
lista_python = range(total)
resultado_python = []

for x in range(total):
    resultado_python = []
    for j in lista_python:
        resultado_python.append(lista_python[j]*2)

print(time.time()-inicio)

inicio = time.time()
lista_ndarray = np.arange(total)

for x in range(total):
    resultado_ndarray = []
    resultado_ndarray = lista_ndarray*2

print(time.time()-inicio)

21.26464009284973
0.050417184829711914


## Arrays de Mais de Uma Dimensão

In [25]:
# array 1D
a = np.arange(12)
print(a)
print(a.shape)
print(a.ndim)
print(a[2])
print()

# array 2D
a = np.arange(12).reshape(3,4)
print(a)
print(a.shape)
print(a.ndim)
print(a[0][3])
print()

# array 3D
a = np.arange(12).reshape(3,2,2)
print(a)
print(a.shape)
print(a.ndim)
print(a[2][0][1])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
1
2

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2
3

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
(3, 2, 2)
3
9


In [31]:
a = np.array([10,40,15,12,4,2,5,7,8,20])
print(a)
print(a[a > 15])

print()

a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a[a > 2])
print(a[a > 2].ndim)

[10 40 15 12  4  2  5  7  8 20]
[40 20]

[[1 2 3]
 [4 5 6]]
[3 4 5 6]
1


In [33]:
zeros = np.zeros((4,5))
print(zeros)
print(zeros.ndim)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
2


In [34]:
print(np.arange(50))
print(np.arange(10,50))
print(np.arange(10,50,5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[10 15 20 25 30 35 40 45]
